using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace FOVPrinter
{
    public class StandardEyePiece
    {
        public StandardEyePiece(string b, string m, float f, float a)
        {
            brand = b;
            model = m;
            focalLength = f;
            apparantFOV = a;
        }
        public string brand { get; set; }
        public string model { get; set; }
        public float focalLength { get; set; }
        public float apparantFOV { get; set; }

        #region standard eye pieces
        public static List<StandardEyePiece> standardEyePieces = new List<StandardEyePiece>()
        {
 new StandardEyePiece("365 Astronomy", "Andromeda Extra Flat", 8f,60f),
 new StandardEyePiece("365 Astronomy", "Andromeda Extra Flat", 12f,60f),
 new StandardEyePiece("365 Astronomy", "Andromeda Extra Flat", 16f,60f),
 new StandardEyePiece("365 Astronomy", "Andromeda Extra Flat", 19f,65f),
 new StandardEyePiece("365 Astronomy", "Andromeda Extra Flat", 27f,58f),
 new StandardEyePiece("365 Astronomy", "Columbus Ultra Wide Angle", 11f,80f),
 new StandardEyePiece("365 Astronomy", "Columbus Ultra Wide Angle", 16f,80f),
 new StandardEyePiece("365 Astronomy", "Magellan Wide Angle", 8f,60f),
 new StandardEyePiece("365 Astronomy", "Magellan Wide Angle", 12f,60f),
 new StandardEyePiece("365 Astronomy", "Magellan Wide Angle", 17f,65f),
 new StandardEyePiece("Agena", "Enhanced Wide Angle", 6f,66f),
 new StandardEyePiece("Agena", "Enhanced Wide Angle", 9f,66f),
 new StandardEyePiece("Agena", "Enhanced Wide Angle", 15f,66f),
 new StandardEyePiece("Agena", "Enhanced Wide Angle", 20f,66f),
 new StandardEyePiece("Agena", "Starguide Dual ED", 3.2f,60f),
 new StandardEyePiece("Agena", "Starguide Dual ED", 5f,60f),
 new StandardEyePiece("Agena", "Starguide Dual ED", 8f,60f),
 new StandardEyePiece("Agena", "Starguide Dual ED", 12f,60f),
 new StandardEyePiece("Agena", "Starguide Dual ED", 15f,60f),
 new StandardEyePiece("Agena", "Starguide Dual ED", 18f,60f),
 new StandardEyePiece("Agena", "Starguide Dual ED", 25f,60f),
 new StandardEyePiece("Agena", "Super Wide Angle SWA", 10f,70f),
 new StandardEyePiece("Agena", "Super Wide Angle SWA", 15f,70f),
 new StandardEyePiece("Agena", "Super Wide Angle SWA", 20f,70f),
 new StandardEyePiece("Agena", "Super Wide Angle SWA", 26f,70f),
 new StandardEyePiece("Agena", "Super Wide Angle SWA", 32f,70f),
 new StandardEyePiece("Agena", "Super Wide Angle SWA", 38f,70f),
 new StandardEyePiece("Agena", "Wide Angle", 8f,60f),
 new StandardEyePiece("Agena", "Wide Angle", 12f,60f),
 new StandardEyePiece("Agena", "Wide Angle", 17f,65f),
 new StandardEyePiece("Agena", "Wide Angle", 20f,65f),


 new StandardEyePiece("Altair Astro (UK)", "Lightwave Hyperwide Premium", 20.00f,100f),
 new StandardEyePiece("Altair Astro (UK)", "Lightwave LER", 3f,55f),
 new StandardEyePiece("Altair Astro (UK)", "Lightwave LER", 5f,55f),
 new StandardEyePiece("Altair Astro (UK)", "Lightwave LER", 6f,55f),
 new StandardEyePiece("Altair Astro (UK)", "Lightwave LER", 9f,55f),
 new StandardEyePiece("Altair Astro (UK)", "Lightwave LER", 12.5f,55f),
 new StandardEyePiece("Altair Astro (UK)", "Lightwave LER Premium", 7f,68f),
 new StandardEyePiece("Altair Astro (UK)", "Lightwave LER Premium", 9f,68f),
 new StandardEyePiece("Altair Astro (UK)", "Lightwave LER Premium", 12f,68f),
 new StandardEyePiece("Altair Astro (UK)", "Lightwave LER Premium", 14.5f,68f),
 new StandardEyePiece("Altair Astro (UK)", "Lightwave LER Premium", 18f,68f),

 new StandardEyePiece("Altair Astro (UK)", "Widefield", 15.00f,70f),
 new StandardEyePiece("Altair Astro (UK)", "Widefield", 20.00f,70f),
 new StandardEyePiece("Andrews (AUS)", "ED ", 18f,55f),
 new StandardEyePiece("Andrews (AUS)", "ED ", 21f,55f),
 new StandardEyePiece("Andrews (AUS)", "ED ", 25f,55f),
 new StandardEyePiece("Andrews (AUS)", "Series 500", 10f,50f),
 new StandardEyePiece("Andrews (AUS)", "Series 500", 15f,50f),
 new StandardEyePiece("Antares", "Classic 2\"", 32f,65f),
 new StandardEyePiece("Antares", "Classic 2\"", 32f,70f),
 new StandardEyePiece("Antares", "SWA (Speers Waler)", 4.9f,82f),
 new StandardEyePiece("Antares", "SWA (Speers Waler)", 7.2f,82f),
 new StandardEyePiece("Antares", "SWA (Speers Waler)", 9.4f,82f),
 new StandardEyePiece("Antares", "SWA (Speers Waler)", 13.4f,80f),
 new StandardEyePiece("Antares", "SWA (Speers Waler)", 17f,78f),
 new StandardEyePiece("Antares", "W70", 4.3f,70f),
 new StandardEyePiece("Antares", "W70", 6f,74f),
 new StandardEyePiece("Antares", "W70", 9.4f,70f),
 new StandardEyePiece("Antares", "W70 Type 2", 9.7f,70f),
 new StandardEyePiece("Antares", "W70 Type 2", 15f,70f),
 new StandardEyePiece("Antares", "W70 Type 2", 25f,70f),
 new StandardEyePiece("Antares", "W70 Type 2", 31f,70f),
 new StandardEyePiece("APM", "Ultra Flat Field", 10f,60f),
 new StandardEyePiece("APM", "Ultra Flat Field", 15f,65f),
 new StandardEyePiece("APM", "Ultra Flat Field", 18f,65f),
 new StandardEyePiece("APM", "Ultra Flat Field", 24f,65f),
 new StandardEyePiece("APM", "Ultra Flat Field", 30f,70f),
 new StandardEyePiece("APM", "Ultra Wide Angle", 30f,80f),
 new StandardEyePiece("Arcturus", "Ebony", 3.5f,70f),
 new StandardEyePiece("Arcturus", "Ebony", 5f,70f),
 new StandardEyePiece("Arcturus", "Ebony", 8f,70f),
 new StandardEyePiece("Arcturus", "Ebony", 13f,70f),
 new StandardEyePiece("Arcturus", "Ebony", 17f,70f),
 new StandardEyePiece("Arcturus", "Ebony", 22f,70f),
 new StandardEyePiece("Arcturus", "Ebony", 32f,70f),
 new StandardEyePiece("Arcturus", "Super Wide Economy", 10f,70f),
 new StandardEyePiece("Arcturus", "Super Wide Economy", 15f,70f),
 new StandardEyePiece("Arcturus", "Super Wide Economy", 20f,70f),
 new StandardEyePiece("Arcturus", "Super Wide Economy", 26f,70f),
 new StandardEyePiece("Arcturus", "Super Wide Economy", 32f,70f),
 new StandardEyePiece("Arcturus", "Super Wide Economy", 38f,70f),
 new StandardEyePiece("Arcturus", "SuperWide", 10f,70f),
 new StandardEyePiece("Arcturus", "Ultra Wide Angle", 11f,80f),
 //new StandardEyePiece("Arcturus", "UltraWide Covertible", 20mm/30mmf,80f),
 new StandardEyePiece("Astro Hutech", "HC Orthoscopic", 4f,42f),
 new StandardEyePiece("Astro Hutech", "HC Orthoscopic", 6f,42f),
 new StandardEyePiece("Astro Hutech", "HC Orthoscopic", 12.5f,42f),
 new StandardEyePiece("Astro Hutech", "HC Orthoscopic", 25f,42f),
 new StandardEyePiece("Astro Professional", "Long Eye Relief", 18f,55f),
 new StandardEyePiece("Astro Tech", "Hi-Grade Plossl", 4f,55f),
 new StandardEyePiece("Astro Tech", "Hi-Grade Plossl", 6f,55f),
 new StandardEyePiece("Astro Tech", "Hi-Grade Plossl", 17f,55f),
 new StandardEyePiece("Astro Tech", "Paradigm Dual ED", 5f,60f),
 new StandardEyePiece("Astro Tech", "Paradigm Dual ED", 8f,60f),
 new StandardEyePiece("Astro Tech", "Paradigm Dual ED", 12f,60f),
 new StandardEyePiece("Astro Tech", "Paradigm Dual ED", 15f,60f),
 new StandardEyePiece("Astro Tech", "Paradigm Dual ED", 18f,60f),
 new StandardEyePiece("Astro Tech", "Paradigm Dual ED", 25f,60f),
 new StandardEyePiece("Astro Tech", "Value Line Plossl", 4f,52f),
 new StandardEyePiece("Astro Tech", "Value Line Plossl", 6f,52f),
 new StandardEyePiece("Astro Tech", "Value Line Plossl", 9f,52f),
 new StandardEyePiece("Astro Tech", "Value Line Plossl", 12f,52f),
 new StandardEyePiece("Astro Tech", "Value Line Plossl", 15f,52f),
 new StandardEyePiece("Astro Tech", "Value Line Plossl", 20f,52f),
 new StandardEyePiece("Astro Tech", "Value Line Plossl", 25f,52f),
 new StandardEyePiece("Astro Tech", "Value Line Plossl", 32f,50f),
 new StandardEyePiece("Astro Tech", "Value Line Plossl", 40f,40f),
 //new StandardEyePiece("Astromania", "eBay merchant selling Chinese clones",  f, f),
 new StandardEyePiece("Baader Planetarium", "Classic Ortho", 6f,49f),
 new StandardEyePiece("Baader Planetarium", "Classic Ortho", 10f,50f),
 new StandardEyePiece("Baader Planetarium", "Classic Ortho", 18f,53f),
 new StandardEyePiece("Baader Planetarium", "Classic Plossl", 32f,43f),
 new StandardEyePiece("Baader Planetarium", "Hyperion", 5f,68f),
 new StandardEyePiece("Baader Planetarium", "Hyperion", 8f,68f),
 new StandardEyePiece("Baader Planetarium", "Hyperion", 10f,68f),
 new StandardEyePiece("Baader Planetarium", "Hyperion", 13f,68f),
 new StandardEyePiece("Baader Planetarium", "Hyperion", 17f,68f),
 new StandardEyePiece("Baader Planetarium", "Hyperion", 21f,68f),
 new StandardEyePiece("Baader Planetarium", "Hyperion", 24f,68f),
 new StandardEyePiece("Baader Planetarium", "Hyperion Ashperic", 31f,70f),
 new StandardEyePiece("Baader Planetarium", "Hyperion Ashperic", 36f,70f),

 new StandardEyePiece("Baader Planetarium", "Morpheus", 4.5f,78f),
 new StandardEyePiece("Baader Planetarium", "Morpheus", 6.5f,78f),
 new StandardEyePiece("Baader Planetarium", "Morpheus", 9f,77f),
 new StandardEyePiece("Baader Planetarium", "Morpheus", 12.5f,77f),
 new StandardEyePiece("Baader Planetarium", "Morpheus", 14f,77f),
 new StandardEyePiece("Baader Planetarium", "Morpheus", 17.5f,77f),
 new StandardEyePiece("Barsta (aka BST)", "58 degree Series", 2.5f,58f),
 new StandardEyePiece("Barsta (aka BST)", "58 degree Series", 3.2f,58f),
 new StandardEyePiece("Barsta (aka BST)", "58 degree Series", 4f,58f),
 new StandardEyePiece("Barsta (aka BST)", "58 degree Series", 4.5f,58f),
 new StandardEyePiece("Barsta (aka BST)", "58 degree Series", 5f,58f),
 new StandardEyePiece("Barsta (aka BST)", "58 degree Series", 6f,58f),
 new StandardEyePiece("Barsta (aka BST)", "58 degree Series", 7f,58f),
 new StandardEyePiece("Barsta (aka BST)", "58 degree Series", 8f,58f),
 new StandardEyePiece("Barsta (aka BST)", "58 degree Series", 9f,58f),
 new StandardEyePiece("Barsta (aka BST)", "58 degree Series", 15f,58f),
 new StandardEyePiece("Barsta (aka BST)", "58 degree Series", 20f,58f),
 new StandardEyePiece("Barsta (aka BST)", "58 degree Series", 25f,58f),
 new StandardEyePiece("Barsta (aka BST)", "Dual ED", 3.2f,60f),
 new StandardEyePiece("Barsta (aka BST)", "Dual ED", 5f,60f),
 new StandardEyePiece("Barsta (aka BST)", "Dual ED", 8f,60f),
 new StandardEyePiece("Barsta (aka BST)", "Dual ED", 12f,60f),
 new StandardEyePiece("Barsta (aka BST)", "Dual ED", 15f,60f),
 new StandardEyePiece("Barsta (aka BST)", "Dual ED", 18f,60f),
 new StandardEyePiece("Barsta (aka BST)", "Dual ED", 25f,60f),
 new StandardEyePiece("Barsta (aka BST)", "Flat Field", 8f,60f),
 new StandardEyePiece("Barsta (aka BST)", "Flat Field", 12f,60f),
 new StandardEyePiece("Barsta (aka BST)", "Flat Field", 16f,60f),
 new StandardEyePiece("Barsta (aka BST)", "Flat Field", 19f,65f),
 new StandardEyePiece("Barsta (aka BST)", "Flat Field", 27f,53f),
 new StandardEyePiece("Brandon", "Brandon Orthoscopic", 6f,42f),
 new StandardEyePiece("Brandon", "Brandon Orthoscopic", 8f,43f),
 new StandardEyePiece("Brandon", "Brandon Orthoscopic", 12f,43f),
 new StandardEyePiece("Brandon", "Brandon Orthoscopic", 16f,43f),
 new StandardEyePiece("Brandon", "Brandon Orthoscopic", 24f,52f),
 new StandardEyePiece("Brandon", "Brandon Orthoscopic", 32f,45f),
 new StandardEyePiece("Brandon", "Brandon Orthoscopic", 48f,45f),
 new StandardEyePiece("Bresser", "Modified Plossl", 5.5f,60f),
 new StandardEyePiece("Bresser", "Modified Plossl", 9f,60f),
 new StandardEyePiece("Bresser", "Modified Plossl", 14f,60f),
 new StandardEyePiece("Bresser", "Modified Plossl", 20f,60f),
 new StandardEyePiece("Bresser", "Modified Plossl", 26f,60f),
 new StandardEyePiece("Bresser", "Modified Plossl", 32f,60f),
 new StandardEyePiece("Bresser", "Modified Plossl", 40f,60f),
 new StandardEyePiece("Bresser", "Super Plossl", 9.5f,52f),
 new StandardEyePiece("Bresser", "Super Plossl", 12.5f,52f),
 new StandardEyePiece("Bresser", "Super Plossl", 15f,52f),
 new StandardEyePiece("Bresser", "Super Plossl", 20f,52f),
 new StandardEyePiece("Bresser", "Super Plossl", 32f,50f),
 new StandardEyePiece("Bresser", "Super Plossl", 40f,40f),
 new StandardEyePiece("Bresser", "Super Plossl", 56f,52f),
 new StandardEyePiece("Bresser", "Wide Angle", 10f,70f),
 new StandardEyePiece("Bresser", "Wide Angle", 15f,70f),
 new StandardEyePiece("Bresser", "Wide Angle", 20f,70f),
 new StandardEyePiece("Bresser", "Wide Angle", 25f,70f),
 new StandardEyePiece("Bresser", "Wide Angle", 30f,70f),
 new StandardEyePiece("Bresser", "Wide Angle", 35f,70f),
 new StandardEyePiece("Burgess Optical  ", "Modified Erfle", 16f,67f),
 new StandardEyePiece("Burgess Optical  ", "Modified Erfle", 24f,67f),
 new StandardEyePiece("Burgess Optical  ", "Modified Erfle", 35f,67f),
 new StandardEyePiece("Burgess Optical  ", "Symmetrical", 12.5f,48f),
 new StandardEyePiece("Burgess Optical  ", "Symmetrical", 30f,55f),
 new StandardEyePiece("Burgess Optical  ", "Symmetrical", 40f,40f),

 new StandardEyePiece("Celestron", "Luminos", 7f,82f),
 new StandardEyePiece("Celestron", "Luminos", 10f,82f),
 new StandardEyePiece("Celestron", "Luminos", 15f,82f),
 new StandardEyePiece("Celestron", "Luminos", 19f,82f),
 new StandardEyePiece("Celestron", "Luminos", 23f,82f),
 new StandardEyePiece("Celestron", "Luminos", 31f,82f),
 new StandardEyePiece("Celestron", "Omni", 4f,50f),
 new StandardEyePiece("Celestron", "Omni", 6f,50f),
 new StandardEyePiece("Celestron", "Omni", 9f,50f),
 new StandardEyePiece("Celestron", "Omni", 12f,50f),
 new StandardEyePiece("Celestron", "Omni", 15f,50f),
 new StandardEyePiece("Celestron", "Omni", 32f,48f),
 new StandardEyePiece("Celestron", "Omni", 40f,40f),
 new StandardEyePiece("Celestron", "Ultima Duo", 5f,68f),
 new StandardEyePiece("Celestron", "Ultima Duo", 8f,68f),
 new StandardEyePiece("Celestron", "Ultima Duo", 10f,68f),
 new StandardEyePiece("Celestron", "Ultima Duo", 13f,68f),
 new StandardEyePiece("Celestron", "Ultima Duo", 17f,68f),
 new StandardEyePiece("Celestron", "Ultima Duo", 21f,68f),
 new StandardEyePiece("Celestron", "X-CEL LX", 2.3f,60f),
 new StandardEyePiece("Celestron", "X-CEL LX", 5f,60f),
 new StandardEyePiece("Celestron", "X-CEL LX", 7f,60f),
 new StandardEyePiece("Celestron", "X-CEL LX", 9f,60f),
 new StandardEyePiece("Celestron", "X-CEL LX", 12f,60f),
 new StandardEyePiece("Celestron", "X-CEL LX", 18f,60f),
 new StandardEyePiece("Celestron", "X-CEL LX", 25f,60f),

 new StandardEyePiece("Coronado", "CeMax", 12f,52.2f),
 new StandardEyePiece("Coronado", "CeMax", 18f,52f),
 new StandardEyePiece("Coronado", "CeMax", 25f,47.2f),
 new StandardEyePiece("Denkmeier Optical", "D14-pr", 14f,65f),
 new StandardEyePiece("Denkmeier Optical", "D21-pr", 21.6f,65f),
 new StandardEyePiece("Discovery", "Plossl", 4f,50f),
 new StandardEyePiece("Discovery", "Plossl", 6.5f,50f),
 new StandardEyePiece("Discovery", "Plossl", 10f,50f),
 new StandardEyePiece("Discovery", "Plossl", 12.5f,50f),
 new StandardEyePiece("Discovery", "Plossl", 15f,50f),
 new StandardEyePiece("Discovery", "Plossl", 20f,50f),
 new StandardEyePiece("Discovery", "Plossl", 25f,50f),
 new StandardEyePiece("Discovery", "Plossl", 30f,50f),
 new StandardEyePiece("Discovery", "Plossl", 40f,40f),
 new StandardEyePiece("Discovery", "Series 70", 10f,70f),
 new StandardEyePiece("Discovery", "Series 70", 15f,70f),
 new StandardEyePiece("Discovery", "Series 70", 20f,70f),
 new StandardEyePiece("Discovery", "Series 70", 32f,70f),


 new StandardEyePiece("Docter", "UWA Astro Eyepiece", 12.5f,84f),
 new StandardEyePiece("Edmund Optics", "Orthoscopic", 4f,41f),
 new StandardEyePiece("Edmund Optics", "Orthoscopic", 6f,43f),
 new StandardEyePiece("Edmund Optics", "Orthoscopic", 12.5f,44f),
 new StandardEyePiece("Edmund Optics", "Orthoscopic", 25f,47f),
 new StandardEyePiece("Edmund Optics", "RKE", 8f,45f),
 new StandardEyePiece("Edmund Optics", "RKE", 12f,46f),
 new StandardEyePiece("Edmund Optics", "RKE", 15f,45f),
 new StandardEyePiece("Edmund Optics", "RKE", 21.5f,47f),
 new StandardEyePiece("Edmund Optics", "RKE", 28.7f,47f),
 new StandardEyePiece("Edmund Scientifics OnLine", "Plossl", 28f,50f),
 new StandardEyePiece("Explore Scientific", "100 Series", 5.5f,100f),
 new StandardEyePiece("Explore Scientific", "100 Series", 9f,100f),
 new StandardEyePiece("Explore Scientific", "100 Series", 14f,100f),
 new StandardEyePiece("Explore Scientific", "100 Series", 20f,100f),
 new StandardEyePiece("Explore Scientific", "100 Series", 25f,100f),
 new StandardEyePiece("Explore Scientific", "120 Series", 9f,120f),
 new StandardEyePiece("Explore Scientific", "3\" Series", 30f,100f),
 new StandardEyePiece("Explore Scientific", "62 Series", 5.5f,62f),
 new StandardEyePiece("Explore Scientific", "62 Series", 9f,62f),
 new StandardEyePiece("Explore Scientific", "62 Series", 14f,62f),
 new StandardEyePiece("Explore Scientific", "62 Series", 20f,62f),
 new StandardEyePiece("Explore Scientific", "62 Series", 26f,62f),
 new StandardEyePiece("Explore Scientific", "62 Series", 32f,62f),
 new StandardEyePiece("Explore Scientific", "62 Series", 40f,62f),
 new StandardEyePiece("Explore Scientific", "68 Series", 16f,68f),
 new StandardEyePiece("Explore Scientific", "68 Series", 20f,68f),
 new StandardEyePiece("Explore Scientific", "68 Series", 24f,68f),
 new StandardEyePiece("Explore Scientific", "68 Series", 28f,68f),
 new StandardEyePiece("Explore Scientific", "68 Series", 34f,68f),
 new StandardEyePiece("Explore Scientific", "68 Series", 40f,68f),
 new StandardEyePiece("Explore Scientific", "82 Series", 4.7f,82f),
 new StandardEyePiece("Explore Scientific", "82 Series", 6.7f,82f),
 new StandardEyePiece("Explore Scientific", "82 Series", 8.8f,82f),
 new StandardEyePiece("Explore Scientific", "82 Series", 11f,82f),
 new StandardEyePiece("Explore Scientific", "82 Series", 14f,82f),
 new StandardEyePiece("Explore Scientific", "82 Series", 18f,82f),
 new StandardEyePiece("Explore Scientific", "82 Series", 24f,82f),
 new StandardEyePiece("Explore Scientific", "82 Series", 30f,82f),
 new StandardEyePiece("Explore Scientific", "92 Series", 12f,92f),
 new StandardEyePiece("Explore Scientific", "92 Series", 17f,92f),
 new StandardEyePiece("Explore Scientific Europe", "MaxVision 68", 20f,68f),
 new StandardEyePiece("Explore Scientific Europe", "MaxVision 68", 28f,68f),
 new StandardEyePiece("Explore Scientific Europe", "MaxVision 68", 34f,68f),
 new StandardEyePiece("Explore Scientific Europe", "MaxVision 68", 40f,68f),
 new StandardEyePiece("Explore Scientific Europe", "MaxVision 82", 24f,82f),
 new StandardEyePiece("Fujiyama", "HD Orthoscopic", 4f,42f),
 new StandardEyePiece("Fujiyama", "HD Orthoscopic", 5f,42f),
 new StandardEyePiece("Fujiyama", "HD Orthoscopic", 6f,42f),
 new StandardEyePiece("Fujiyama", "HD Orthoscopic", 7f,42f),
 new StandardEyePiece("Fujiyama", "HD Orthoscopic", 9f,42f),
 new StandardEyePiece("Fujiyama", "HD Orthoscopic", 12.5f,42f),
 new StandardEyePiece("Fujiyama", "HD Orthoscopic", 18f,42f),
 new StandardEyePiece("Fujiyama", "HD Orthoscopic", 25f,42f),
 new StandardEyePiece("Garrett Optical", "Plossl", 12.5f,52f),
 new StandardEyePiece("GSO (Guan Sheng Optical)", "Plossl", 4f,50f),
 new StandardEyePiece("GSO (Guan Sheng Optical)", "Plossl", 6f,50f),
 new StandardEyePiece("GSO (Guan Sheng Optical)", "Plossl", 9f,50f),
 new StandardEyePiece("GSO (Guan Sheng Optical)", "Plossl", 12f,50f),
 new StandardEyePiece("GSO (Guan Sheng Optical)", "Plossl", 15f,50f),
 new StandardEyePiece("GSO (Guan Sheng Optical)", "Plossl", 20f,50f),
 new StandardEyePiece("GSO (Guan Sheng Optical)", "Plossl", 25f,50f),
 new StandardEyePiece("GSO (Guan Sheng Optical)", "Plossl", 32f,50f),
 new StandardEyePiece("GSO (Guan Sheng Optical)", "Plossl", 40f,40f),
 new StandardEyePiece("GSO (Guan Sheng Optical)", "Superview", 15f,65f),
 new StandardEyePiece("GSO (Guan Sheng Optical)", "Superview", 20f,67f),
 new StandardEyePiece("GSO (Guan Sheng Optical)", "Superview", 30f,70f),
 new StandardEyePiece("GSO (Guan Sheng Optical)", "Superview", 42f,58f),
 new StandardEyePiece("GSO (Guan Sheng Optical)", "Superview", 50f,48f),
 //new StandardEyePiece("Harry Siebert Optics", "Monocentric", 38.9f,?f),
 //new StandardEyePiece("Harry Siebert Optics", "Monocentric", 50f,?f),
 //new StandardEyePiece("Harry Siebert Optics", "Monocentric (add $199 for barlow)", 10f,?f),
 //new StandardEyePiece("Harry Siebert Optics", "Monocentric (add $199 for barlow)", 12f,?f),
 //new StandardEyePiece("Harry Siebert Optics", "Monocentric (add $199 for barlow)", 14.5f,?f),
 //new StandardEyePiece("Harry Siebert Optics", "Monocentric (add $199 for barlow)", 17.5f,?f),
 //new StandardEyePiece("Harry Siebert Optics", "Monocentric (add $199 for barlow)", 20f,?f),
 //new StandardEyePiece("Harry Siebert Optics", "Monocentric (add $199 for barlow)", 24.5f,?f),
 //new StandardEyePiece("Harry Siebert Optics", "Observatory Elite Series", 40f,75f),
 new StandardEyePiece("Harry Siebert Optics", "Observatory Elite Series", 40f,75f),
 new StandardEyePiece("Harry Siebert Optics", "Observatory Elite Series", 40f,75f),
 new StandardEyePiece("Harry Siebert Optics", "Observatory Elite Series", 40f,75f),
 new StandardEyePiece("Harry Siebert Optics", "Observatory Elite Series", 40f,75f),
 new StandardEyePiece("Harry Siebert Optics", "Observatory Elite Series", 42f,75f),
 new StandardEyePiece("Harry Siebert Optics", "Observatory Elite Series", 42f,75f),
 new StandardEyePiece("Harry Siebert Optics", "Observatory Elite Series", 42f,75f),
 new StandardEyePiece("Harry Siebert Optics", "Observatory Elite Series", 42f,75f),
 new StandardEyePiece("Harry Siebert Optics", "Observatory Elite Series", 42f,75f),
 new StandardEyePiece("Harry Siebert Optics", "Observatory Elite Series", 50f,70f),
 new StandardEyePiece("Harry Siebert Optics", "Observatory Elite Series", 50f,70f),
 new StandardEyePiece("Harry Siebert Optics", "Observatory Elite Series", 50f,70f),
 new StandardEyePiece("Harry Siebert Optics", "Observatory Elite Series", 50f,70f),
 new StandardEyePiece("Harry Siebert Optics", "Observatory Elite Series", 50f,70f),
 new StandardEyePiece("Harry Siebert Optics", "Observatory Elite Series", 55f,63f),
 new StandardEyePiece("Harry Siebert Optics", "Observatory Elite Series", 55f,65f),
 new StandardEyePiece("Harry Siebert Optics", "Observatory Elite Series", 55f,70f),
 new StandardEyePiece("Harry Siebert Optics", "Observatory Elite Series", 55f,70f),
 new StandardEyePiece("Harry Siebert Optics", "Observatory Elite Series", 55f,70f),
 new StandardEyePiece("Harry Siebert Optics", "Observatory Elite Series", 60f,57f),
 new StandardEyePiece("Harry Siebert Optics", "Observatory Elite Series", 60f,60f),
 new StandardEyePiece("Harry Siebert Optics", "Observatory Elite Series", 60f,65f),
 new StandardEyePiece("Harry Siebert Optics", "Observatory Elite Series", 60f,70f),
 new StandardEyePiece("Harry Siebert Optics", "Observatory Elite Series", 60f,70f),
 new StandardEyePiece("Harry Siebert Optics", "Observatory Elite Series", 65f,53f),
 new StandardEyePiece("Harry Siebert Optics", "Observatory Elite Series", 65f,56f),
 new StandardEyePiece("Harry Siebert Optics", "Observatory Elite Series", 65f,65f),
 new StandardEyePiece("Harry Siebert Optics", "Observatory Elite Series", 65f,65f),
 new StandardEyePiece("Harry Siebert Optics", "Observatory Elite Series", 65f,65f),
 new StandardEyePiece("Harry Siebert Optics", "Observatory Elite Series", 70f,50f),
 new StandardEyePiece("Harry Siebert Optics", "Observatory Elite Series", 70f,52f),
 new StandardEyePiece("Harry Siebert Optics", "Observatory Elite Series", 70f,60f),
 new StandardEyePiece("Harry Siebert Optics", "Observatory Elite Series", 70f,65f),
 new StandardEyePiece("Harry Siebert Optics", "Observatory Elite Series", 70f,65f),
 new StandardEyePiece("Harry Siebert Optics", "Observatory Elite Series", 75f,60f),
 new StandardEyePiece("Harry Siebert Optics", "Observatory Elite Series", 75f,60f),
 new StandardEyePiece("Harry Siebert Optics", "Observatory Elite Series", 75f,60f),
 new StandardEyePiece("Harry Siebert Optics", "Observatory Elite Series", 80f,60f),
 new StandardEyePiece("Harry Siebert Optics", "Observatory Elite Series", 80f,60f),
 new StandardEyePiece("Harry Siebert Optics", "Observatory Elite Series", 80f,60f),
 new StandardEyePiece("Harry Siebert Optics", "Observatory Elite Series", 85f,57f),
 new StandardEyePiece("Harry Siebert Optics", "Observatory Elite Series", 85f,57f),
 new StandardEyePiece("Harry Siebert Optics", "Observatory Elite Series", 90f,55f),
 new StandardEyePiece("Harry Siebert Optics", "Observatory Elite Series", 90f,55f),
 new StandardEyePiece("Harry Siebert Optics", "Observatory Elite Series", 95f,55f),
 new StandardEyePiece("Harry Siebert Optics", "Observatory Elite Series", 95f,55f),
 new StandardEyePiece("Harry Siebert Optics", "Observatory Elite Series", 100f,55f),
 new StandardEyePiece("Harry Siebert Optics", "Observatory Elite Series", 100f,55f),
 new StandardEyePiece("Harry Siebert Optics", "Observatory Series", 34f,65f),
 new StandardEyePiece("Harry Siebert Optics", "Observatory Series", 36f,65f),
 new StandardEyePiece("Harry Siebert Optics", "Performance +", 9f,60f),
 new StandardEyePiece("Harry Siebert Optics", "Performance +", 10f,60f),
 new StandardEyePiece("Harry Siebert Optics", "Performance +", 14f,60f),
 new StandardEyePiece("Harry Siebert Optics", "Performance +", 17f,60f),
 new StandardEyePiece("Harry Siebert Optics", "Performance +", 18f,60f),
 new StandardEyePiece("Harry Siebert Optics", "Performance +", 35f,49f),
 //new StandardEyePiece("Harry Siebert Optics", "Planesphere BK7", 3.5f,?f),
 //new StandardEyePiece("Harry Siebert Optics", "Planesphere BK7", 4.5f,?f),
 //new StandardEyePiece("Harry Siebert Optics", "Planesphere BK7", 6f,?f),
 //new StandardEyePiece("Harry Siebert Optics", "Planesphere BK7", 7.5f,?f),
 //new StandardEyePiece("Harry Siebert Optics", "Planesphere Fused Silica", 3f,?f),
 //new StandardEyePiece("Harry Siebert Optics", "Planesphere Fused Silica", 4f,?f),
 //new StandardEyePiece("Harry Siebert Optics", "Planesphere Fused Silica", 5f,?f),
 //new StandardEyePiece("Harry Siebert Optics", "Planesphere Fused Silica", 6.5f,?f),
 new StandardEyePiece("Harry Siebert Optics", "Starsplitter SS3 Series", 2.9f,60f),
 new StandardEyePiece("Harry Siebert Optics", "Starsplitter SS3 Series", 3.4f,60f),
 new StandardEyePiece("Harry Siebert Optics", "Starsplitter SS3 Series", 3.9f,60f),
 new StandardEyePiece("Harry Siebert Optics", "Starsplitter SS3 Series", 4.4f,60f),
 new StandardEyePiece("Harry Siebert Optics", "Starsplitter SS3 Series", 4.9f,60f),
 new StandardEyePiece("Harry Siebert Optics", "Starsplitter SS3 Series", 5.4f,60f),
 new StandardEyePiece("Harry Siebert Optics", "Starsplitter SS3 Series", 5.9f,60f),
 new StandardEyePiece("Harry Siebert Optics", "Starsplitter SS3 Series", 6.4f,60f),
 new StandardEyePiece("Harry Siebert Optics", "Starsplitter SS3 Series", 6.9f,60f),
 new StandardEyePiece("Harry Siebert Optics", "Starsplitter SS3 Series", 7.4f,60f),
 new StandardEyePiece("Harry Siebert Optics", "Starsplitter SS3 Series", 7.9f,60f),
 new StandardEyePiece("Harry Siebert Optics", "Starsplitter SS3 Series", 8.9f,60f),
 new StandardEyePiece("Harry Siebert Optics", "Starsplitter SS3 Series", 9.4f,60f),
 new StandardEyePiece("Harry Siebert Optics", "Starsplitter SS3 Series", 9.9f,60f),
 new StandardEyePiece("Harry Siebert Optics", "Starsplitter SS4 Series", 3.9f,60f),
 new StandardEyePiece("Harry Siebert Optics", "Starsplitter SS4 Series", 4.4f,60f),
 new StandardEyePiece("Harry Siebert Optics", "Starsplitter SS4 Series", 4.9f,60f),
 new StandardEyePiece("Harry Siebert Optics", "Starsplitter SS4 Series", 5.4f,60f),
 new StandardEyePiece("Harry Siebert Optics", "Starsplitter SS4 Series", 5.9f,60f),
 new StandardEyePiece("Harry Siebert Optics", "Starsplitter SS4 Series", 6.4f,60f),
 new StandardEyePiece("Harry Siebert Optics", "Starsplitter SS4 Series", 6.9f,60f),
 new StandardEyePiece("Harry Siebert Optics", "Starsplitter SS4 Series", 7.4f,60f),
 new StandardEyePiece("Harry Siebert Optics", "Starsplitter SS4 Series", 7.9f,60f),
 new StandardEyePiece("Harry Siebert Optics", "Starsplitter SS4 Series", 8.9f,60f),
 new StandardEyePiece("Harry Siebert Optics", "Starsplitter SS4 Series", 9.4f,60f),
 new StandardEyePiece("Harry Siebert Optics", "Starsplitter SS4 Series", 9.9f,60f),
 new StandardEyePiece("Harry Siebert Optics", "Starsplitter SS4 Series", 14f,60f),
 new StandardEyePiece("Harry Siebert Optics", "Starsplitter SS4 Series", 18f,60f),
 new StandardEyePiece("Harry Siebert Optics", "Ultra", 7f,70f),
 new StandardEyePiece("Harry Siebert Optics", "Ultra", 7f,70f),
 new StandardEyePiece("Harry Siebert Optics", "Ultra", 9f,70f),
 new StandardEyePiece("Harry Siebert Optics", "Ultra", 9f,70f),
 new StandardEyePiece("Harry Siebert Optics", "Ultra", 10f,70f),
 new StandardEyePiece("Harry Siebert Optics", "Ultra", 10f,70f),
 new StandardEyePiece("Harry Siebert Optics", "Ultra", 11f,70f),
 new StandardEyePiece("Harry Siebert Optics", "Ultra", 11f,70f),
 new StandardEyePiece("Harry Siebert Optics", "Ultra", 13f,70f),
 new StandardEyePiece("Harry Siebert Optics", "Ultra", 13f,70f),
 new StandardEyePiece("Harry Siebert Optics", "Ultra", 15f,70f),
 new StandardEyePiece("Harry Siebert Optics", "Ultra", 15f,70f),
 new StandardEyePiece("Harry Siebert Optics", "Ultra", 17f,70f),
 new StandardEyePiece("Harry Siebert Optics", "Ultra", 17f,70f),
 new StandardEyePiece("Harry Siebert Optics", "Ultra", 18f,70f),
 new StandardEyePiece("Harry Siebert Optics", "Ultra", 18f,70f),
 new StandardEyePiece("Harry Siebert Optics", "Ultra", 19f,70f),
 new StandardEyePiece("Harry Siebert Optics", "Ultra", 19f,70f),
 new StandardEyePiece("Harry Siebert Optics", "Ultra", 24f,65f),
 new StandardEyePiece("Harry Siebert Optics", "Ultra", 24f,65f),
 new StandardEyePiece("Harry Siebert Optics", "Ultra", 28f,58f),
 new StandardEyePiece("Harry Siebert Optics", "Ultra", 28f,58f),
 new StandardEyePiece("Harry Siebert Optics", "Ultra", 35f,45f),
 new StandardEyePiece("Harry Siebert Optics", "Ultra", 35f,45f),
 new StandardEyePiece("High Point", "Plossl", 4f,50f),
 new StandardEyePiece("High Point", "Plossl", 6f,50f),
 new StandardEyePiece("High Point", "Plossl", 9f,50f),
 new StandardEyePiece("High Point", "Plossl", 12f,50f),
 new StandardEyePiece("High Point", "Plossl", 15f,50f),
 new StandardEyePiece("High Point", "Plossl", 20f,50f),
 new StandardEyePiece("High Point", "Plossl", 25f,50f),
 new StandardEyePiece("High Point", "Plossl", 32f,50f),
 new StandardEyePiece("High Point", "Plossl", 40f,40f),
 new StandardEyePiece("High Point", "SuperView", 15f,65f),
 new StandardEyePiece("High Point", "SuperView", 20f,67f),
 new StandardEyePiece("High Point", "SuperView", 30f,70f),
 new StandardEyePiece("High Point", "SuperView", 42f,58f),
 new StandardEyePiece("High Point", "SuperView", 50f,48f),
 new StandardEyePiece("Kasai Trading", "Astroplan", 5f,50f),
 new StandardEyePiece("Kasai Trading", "Astroplan", 7.5f,50f),
 new StandardEyePiece("Kasai Trading", "Astroplan", 10f,50f),
 new StandardEyePiece("Kasai Trading", "Astroplan", 12.5f,50f),
 new StandardEyePiece("Kasai Trading", "Astroplan", 15f,50f),
 new StandardEyePiece("Kasai Trading", "Extra Wide View", 10f,85f),
 new StandardEyePiece("Kitakaruizawa Observatory", "Cosmic Blue", 20f,70f),
 new StandardEyePiece("Kitakaruizawa Observatory", "Lavendura", 30f,43f),
 new StandardEyePiece("Kitakaruizawa Observatory", "Lavendura", 40f,40f),
 new StandardEyePiece("Kitakaruizawa Observatory", "Lavendura", 50f,45f),
 new StandardEyePiece("Kitakaruizawa Observatory", "Lavendura", 63f,45f),
 new StandardEyePiece("Kitakura", "RPL", 18f,62f),
 new StandardEyePiece("Kitakura", "RPL", 25f,62f),
 new StandardEyePiece("Kitakura", "RPL", 30f,62f),
 new StandardEyePiece("Kitakura", "RPL", 40f,65f),
 new StandardEyePiece("Kitakura", "RPL", 45f,62f),
 new StandardEyePiece("KnightOwl", "Enhanced Super Wide", 6f,66f),
 new StandardEyePiece("KnightOwl", "Enhanced Super Wide", 9f,66f),
 new StandardEyePiece("KnightOwl", "Enhanced Super Wide", 15f,66f),
 new StandardEyePiece("KnightOwl", "Enhanced Super Wide", 20f,66f),
 new StandardEyePiece("KnightOwl", "Hi-Res Planetary", 2.5f,58f),
 new StandardEyePiece("KnightOwl", "Hi-Res Planetary", 3.2f,58f),
 new StandardEyePiece("KnightOwl", "Hi-Res Planetary", 4f,58f),
 new StandardEyePiece("KnightOwl", "Hi-Res Planetary", 5f,58f),
 new StandardEyePiece("KnightOwl", "Hi-Res Planetary", 6f,58f),
 new StandardEyePiece("KnightOwl", "Hi-Res Planetary", 7.5f,58f),
 new StandardEyePiece("KnightOwl", "Hi-Res Planetary", 9f,58f),
 new StandardEyePiece("KnightOwl", "MC", 4f,50f),
 new StandardEyePiece("KnightOwl", "MC", 6.5f,50f),
 new StandardEyePiece("KnightOwl", "MC", 10f,50f),
 new StandardEyePiece("KnightOwl", "MC", 12.5f,50f),
 new StandardEyePiece("KnightOwl", "MC", 15f,50f),
 new StandardEyePiece("KnightOwl", "MC", 20f,50f),
 new StandardEyePiece("KnightOwl", "MC", 25f,50f),
 new StandardEyePiece("KnightOwl", "MC", 30f,50f),
 new StandardEyePiece("KnightOwl", "MC", 40f,40f),
 new StandardEyePiece("KnightOwl", "Ultra-Wide", 11f,80f),
 new StandardEyePiece("KnightOwl", "Ultra-Wide", 15f,80f),
 new StandardEyePiece("KnightOwl", "Ultra-Wide", 16f,80f),
 new StandardEyePiece("KnightOwl", "Ultra-Wide", 20f,80f),
 new StandardEyePiece("KnightOwl", "Ultra-Wide", 30f,80f),
 //new StandardEyePiece("KSON ", "Erfle", 26f,f),
 //new StandardEyePiece("KSON ", "Kellner", 32f,f),
 //new StandardEyePiece("KSON ", "Orthoscopic", 4.8f,f),
 //new StandardEyePiece("KSON ", "Orthoscopic", 7.7f,f),
 //new StandardEyePiece("KSON ", "Orthoscopic", 10.5f,f),
 //new StandardEyePiece("KSON ", "Orthoscopic", 16.8f,f),
 //new StandardEyePiece("KSON ", "Orthoscopic", 24f,f),
 //new StandardEyePiece("KSON ", "Plossl", 7.7f,f),
 //new StandardEyePiece("KSON ", "Plossl", 10f,f),
 //new StandardEyePiece("KSON ", "Plossl", 25f,f),
 //new StandardEyePiece("KSON ", "Plossl", 32f,f),
 //new StandardEyePiece("Lederman", "L-O-A 3D binoviewer EP--PER PAIR", 21f,65f),

 new StandardEyePiece("Levenhuk", "Kellner", 6.3f,50f),
 new StandardEyePiece("Levenhuk", "Kellner", 26f,65f),
 new StandardEyePiece("Levenhuk", "Kellner", 32f,65f),
 new StandardEyePiece("Levenhuk", "Kellner", 40f,65f),
 new StandardEyePiece("Levenhuk", "Plossl", 4f,50f),
 new StandardEyePiece("Levenhuk", "Plossl", 6f,50f),
 new StandardEyePiece("Levenhuk", "Plossl", 6.3f,50f),
 new StandardEyePiece("Levenhuk", "Plossl", 6.5f,52f),
 new StandardEyePiece("Levenhuk", "Plossl", 7.5f,50f),
 new StandardEyePiece("Levenhuk", "Plossl", 9f,50f),
 new StandardEyePiece("Levenhuk", "Plossl", 12f,50f),
 new StandardEyePiece("Levenhuk", "Plossl", 15f,50f),
 new StandardEyePiece("Levenhuk", "Plossl", 20f,50f),
 new StandardEyePiece("Levenhuk", "Plossl", 25f,50f),
 new StandardEyePiece("Levenhuk", "Plossl", 32f,50f),
 new StandardEyePiece("Levenhuk", "Plossl", 40f,40f),
 new StandardEyePiece("Levenhuk", "Ra 82 degree", 4f,82f),
 new StandardEyePiece("Levenhuk", "Ra 82 degree", 7f,82f),
 new StandardEyePiece("Levenhuk", "Ra 82 degree", 16f,76f),
 new StandardEyePiece("Levenhuk", "Ra 82 degree", 28f,79f),
 new StandardEyePiece("Levenhuk", "Ra ED", 30f,68f),
 new StandardEyePiece("Levenhuk", "Ra ED", 35f,68f),
 new StandardEyePiece("Levenhuk", "Ra ED", 40f,68f),
 new StandardEyePiece("Levenhuk", "Ra ER20", 3.5f,68f),
 new StandardEyePiece("Levenhuk", "Ra ER20", 7f,68f),
 new StandardEyePiece("Levenhuk", "Ra ER20", 9f,68f),
 new StandardEyePiece("Levenhuk", "Ra ER20", 12f,68f),
 new StandardEyePiece("Levenhuk", "Ra ER20", 14.5f,68f),
 new StandardEyePiece("Levenhuk", "Ra ER20", 18f,68f),
 new StandardEyePiece("Levenhuk", "Ra Flat Field", 8f,68f),
 new StandardEyePiece("Levenhuk", "Ra Flat Field", 12f,60f),
 new StandardEyePiece("Levenhuk", "Ra Flat Field", 16f,60f),
 new StandardEyePiece("Levenhuk", "Ra Flat Field", 19f,65f),
 new StandardEyePiece("Levenhuk", "Ra Flat Field", 27f,53f),
 new StandardEyePiece("Levenhuk", "Ra LER", 3f,55f),
 new StandardEyePiece("Levenhuk", "Ra LER", 5f,55f),
 new StandardEyePiece("Levenhuk", "Ra LER", 6f,55f),
 new StandardEyePiece("Levenhuk", "Ra LER", 18f,55f),
 new StandardEyePiece("Levenhuk", "Ra Plossl", 4f,55f),
 new StandardEyePiece("Levenhuk", "Ra Plossl", 6f,55f),
 new StandardEyePiece("Levenhuk", "Ra Plossl", 12.5f,55f),
 new StandardEyePiece("Levenhuk", "Ra Plossl", 17f,55f),
 new StandardEyePiece("Levenhuk", "Ra Plossl", 20f,55f),
 new StandardEyePiece("Levenhuk", "Ra Plossl", 25f,55f),
 new StandardEyePiece("Levenhuk", "Ra Plossl", 30f,55f),
 new StandardEyePiece("Levenhuk", "Ra Plossl", 40f,55f),


 new StandardEyePiece("Levenhuk", "Super Plossl", 6.3f,52f),
 new StandardEyePiece("Levenhuk", "Super Plossl", 7.5f,52f),
 new StandardEyePiece("Levenhuk", "SuperView", 15f,68f),
 new StandardEyePiece("Levenhuk", "SuperView", 20f,68f),
 new StandardEyePiece("Levenhuk", "SuperView", 30f,68f),
 new StandardEyePiece("Levenhuk", "SuperView", 42f,60f),
 new StandardEyePiece("Levenhuk", "SuperView", 50f,48f),


 new StandardEyePiece("Lunt", "Solar Eyepieces", 8f,53f),
 new StandardEyePiece("Lunt", "Solar Eyepieces", 12f,60f),
 new StandardEyePiece("Lunt", "Solar Eyepieces", 16f,60f),
 new StandardEyePiece("Lunt", "Solar Eyepieces", 19f,65f),
 new StandardEyePiece("Lunt", "Solar Eyepieces", 27f,55f),
 new StandardEyePiece("Lunt", "XWA", 3.50f,110f),
 new StandardEyePiece("Lunt", "XWA", 4.77f,110f),
 new StandardEyePiece("Lunt", "XWA", 9.00f,100f),
 new StandardEyePiece("Lunt", "XWA", 20.00f,100f),

 new StandardEyePiece("Masuyama", "Masuyama", 45f,53f),
 new StandardEyePiece("Masuyama", "Masuyama", 50f,53f),
 new StandardEyePiece("Masuyama", "Masuyama", 60f,46f),
 new StandardEyePiece("Masuyama", "Masuyama", 80f,52f),
 new StandardEyePiece("Masuyama", "Widefield", 26f,85f),
 new StandardEyePiece("Masuyama", "Widefield", 32f,85f),
 new StandardEyePiece("Meade", "Mega Wide Angle", 5f,100f),
 new StandardEyePiece("Meade", "Mega Wide Angle", 10f,100f),
 new StandardEyePiece("Meade", "Mega Wide Angle", 15f,100f),
 new StandardEyePiece("Meade", "Mega Wide Angle", 21f,100f),
 new StandardEyePiece("Meade", "Series 5000 HD-60 ", 4.5f,60f),
 new StandardEyePiece("Meade", "Series 5000 HD-60 ", 6.5f,60f),
 new StandardEyePiece("Meade", "Series 5000 HD-60 ", 9f,60f),
 new StandardEyePiece("Meade", "Series 5000 HD-60 ", 12f,60f),
 new StandardEyePiece("Meade", "Series 5000 HD-60 ", 18f,60f),
 new StandardEyePiece("Meade", "Series 5000 HD-60 ", 25f,60f),
 new StandardEyePiece("Meade", "Series 5000 Ultra Wide Angle", 5.5f,82f),
 new StandardEyePiece("Meade", "Series 5000 Ultra Wide Angle", 8.8f,82f),
 new StandardEyePiece("Meade", "Series 5000 Ultra Wide Angle", 14f,82f),
 new StandardEyePiece("Meade", "Series 5000 Ultra Wide Angle", 20f,82f),
 new StandardEyePiece("Meade", "Series4000SuperPlossl", 6.4f,52f),
 new StandardEyePiece("Meade", "Series4000SuperPlossl", 9.7f,52f),
 new StandardEyePiece("Meade", "Series4000SuperPlossl", 12.4f,52f),
 new StandardEyePiece("Meade", "Series4000SuperPlossl", 15f,52f),
 new StandardEyePiece("Meade", "Series4000SuperPlossl", 20f,52f),
 new StandardEyePiece("Meade", "Series4000SuperPlossl", 26f,52f),
 new StandardEyePiece("Meade", "Series4000SuperPlossl", 32f,50f),
 new StandardEyePiece("Meade", "Series4000SuperPlossl", 40f,40f),
 new StandardEyePiece("Meade", "Series4000SuperPlossl", 56f,52f),


 new StandardEyePiece("Moonfish", "Superview", 15f,68f),
 new StandardEyePiece("Moonfish", "Superview", 20f,68f),
 new StandardEyePiece("Moonfish", "Ultra Wide", 15f,80f),
 new StandardEyePiece("Moonfish", "Ultra Wide", 30f,80f),
 new StandardEyePiece("Nikon", "NAV-HW", 12.5f,102f),
 new StandardEyePiece("Nikon", "NAV-HW", 17f,102f),
 new StandardEyePiece("Nikon", "NAV-SW", 5f,74f),
 new StandardEyePiece("Nikon", "NAV-SW", 7f,72f),
 new StandardEyePiece("Nikon", "NAV-SW", 10f,74f),
 new StandardEyePiece("Nikon", "NAV-SW", 14f,72f),
 new StandardEyePiece("Nikon", "NAV-SW", 17.5f,68f),
 new StandardEyePiece("Olivon ", "70 degree Series", 3.5f,70f),
 new StandardEyePiece("Olivon ", "70 degree Series", 5f,70f),
 new StandardEyePiece("Olivon ", "70 degree Series", 8f,70f),
 new StandardEyePiece("Olivon ", "70 degree Series", 13f,70f),
 new StandardEyePiece("Olivon ", "70 degree Series", 17f,70f),
 new StandardEyePiece("Olivon ", "70 degree Series", 22f,70f),
 new StandardEyePiece("Olivon ", "70 degree Series", 32f,70f),
 new StandardEyePiece("Olivon ", "High Definition", 2.5f,58f),
 new StandardEyePiece("Olivon ", "High Definition", 4f,58f),
 new StandardEyePiece("Olivon ", "High Definition", 5f,58f),
 new StandardEyePiece("Olivon ", "High Definition", 6f,58f),
 new StandardEyePiece("Olivon ", "High Definition", 7f,58f),
 new StandardEyePiece("Olivon ", "High Definition", 15f,58f),
 new StandardEyePiece("Olivon ", "High Definition", 20f,58f),
 new StandardEyePiece("Olivon ", "Superwide ED", 11f,80f),
 new StandardEyePiece("Olivon ", "Superwide ED", 15f,80f),
 new StandardEyePiece("Olivon ", "Superwide ED", 16f,80f),
 new StandardEyePiece("Olivon ", "Superwide ED", 20f,80f),
 new StandardEyePiece("Olivon ", "Superwide ED", 30f,80f),



 new StandardEyePiece("Omegon", "Cronus", 2.5f,58f),
 new StandardEyePiece("Omegon", "Cronus", 3.2f,58f),
 new StandardEyePiece("Omegon", "Cronus", 4f,58f),
 new StandardEyePiece("Omegon", "Cronus", 5f,58f),
 new StandardEyePiece("Omegon", "Cronus", 6f,58f),
 new StandardEyePiece("Omegon", "Cronus", 7f,58f),
 new StandardEyePiece("Omegon", "Cronus", 8f,58f),
 new StandardEyePiece("Omegon", "Cronus", 9f,58f),

 new StandardEyePiece("Omegon", "Flatfield", 8f,60f),
 new StandardEyePiece("Omegon", "Flatfield", 12f,60f),
 new StandardEyePiece("Omegon", "Flatfield", 16f,60f),
 new StandardEyePiece("Omegon", "Flatfield", 19f,65f),
 new StandardEyePiece("Omegon", "Flatfield", 27f,53f),
 new StandardEyePiece("Omegon", "Flatfield ED", 5f,60f),
 new StandardEyePiece("Omegon", "Flatfield ED", 8f,60f),
 new StandardEyePiece("Omegon", "Flatfield ED", 12f,60f),
 new StandardEyePiece("Omegon", "Flatfield ED", 15f,60f),
 new StandardEyePiece("Omegon", "Flatfield ED", 18f,60f),
 new StandardEyePiece("Omegon", "Flatfield ED", 25f,60f),

 new StandardEyePiece("Omegon", "LE Planetary", 3f,55f),
 new StandardEyePiece("Omegon", "LE Planetary", 5f,55f),
 new StandardEyePiece("Omegon", "LE Planetary", 6f,55f),
 new StandardEyePiece("Omegon", "LE Planetary", 9f,55f),
 new StandardEyePiece("Omegon", "LE Planetary", 14.5f,55f),
 new StandardEyePiece("Omegon", "LE Planetary", 18f,55f),
 new StandardEyePiece("Omegon", "Oberon", 7f,82f),
 new StandardEyePiece("Omegon", "Oberon", 10.00f,82f),
 new StandardEyePiece("Omegon", "Oberon", 15f,82f),
 new StandardEyePiece("Omegon", "Oberon", 19f,82f),
 new StandardEyePiece("Omegon", "Oberon", 23f,82f),
 new StandardEyePiece("Omegon", "Oberon", 32f,82f),
 new StandardEyePiece("Omegon", "Ortho", 10.50f,48f),
 new StandardEyePiece("Omegon", "Ortho", 16.80f,48f),
 new StandardEyePiece("Omegon", "Ortho", 24.00f,48f),
 new StandardEyePiece("Omegon", "Plossl", 4f,50f),
 new StandardEyePiece("Omegon", "Plossl", 6.3f,50f),
 new StandardEyePiece("Omegon", "Plossl", 10f,50f),
 new StandardEyePiece("Omegon", "Plossl", 12.5f,50f),
 new StandardEyePiece("Omegon", "Plossl", 15f,50f),
 new StandardEyePiece("Omegon", "Plossl", 17f,50f),
 new StandardEyePiece("Omegon", "Plossl", 20f,50f),
 new StandardEyePiece("Omegon", "Plossl", 25f,50f),
 new StandardEyePiece("Omegon", "Plossl", 32f,50f),
 new StandardEyePiece("Omegon", "Plossl", 40f,40f),
 new StandardEyePiece("Omegon", "Redline", 3.5f,70f),
 new StandardEyePiece("Omegon", "Redline", 5f,70f),
 new StandardEyePiece("Omegon", "Redline", 8f,70f),
 new StandardEyePiece("Omegon", "Redline", 13f,70f),
 new StandardEyePiece("Omegon", "Redline", 17f,70f),
 new StandardEyePiece("Omegon", "Redline", 22f,70f),
 new StandardEyePiece("Omegon", "Redline", 32f,70f),
 new StandardEyePiece("Omegon", "Super LE  ", 9f,68f),
 new StandardEyePiece("Omegon", "Super LE  ", 12f,68f),
 new StandardEyePiece("Omegon", "Super LE  ", 14.5f,68f),
 new StandardEyePiece("Omegon", "Super LE  ", 18f,68f),
 new StandardEyePiece("Omegon", "Super LE  (replaces 3.5 and 5mm)", 7f,68f),
 new StandardEyePiece("Omegon", "Super Plossl", 4f,52f),
 new StandardEyePiece("Omegon", "Super Plossl", 6.3f,52f),
 new StandardEyePiece("Omegon", "Super Plossl", 10f,52f),
 new StandardEyePiece("Omegon", "Super Plossl", 15f,52f),
 new StandardEyePiece("Omegon", "Super Plossl", 17f,52f),
 new StandardEyePiece("Omegon", "Super Plossl", 20f,52f),
 new StandardEyePiece("Omegon", "Super Plossl", 20f,52f),
 new StandardEyePiece("Omegon", "Super Plossl", 25f,52f),
 new StandardEyePiece("Omegon", "Super Plossl", 26f,52f),
 new StandardEyePiece("Omegon", "Super Plossl", 32f,50f),
 new StandardEyePiece("Omegon", "Super Plossl", 40f,40f),
 new StandardEyePiece("Omegon", "Super Plossl", 56f,52f),
 new StandardEyePiece("Omegon", "SWA", 10f,70f),
 new StandardEyePiece("Omegon", "SWA", 15f,70f),
 new StandardEyePiece("Omegon", "SWA", 20f,70f),
 new StandardEyePiece("Omegon", "SWA", 26f,70f),
 new StandardEyePiece("Omegon", "SWA", 32f,70f),
 new StandardEyePiece("Omegon", "SWA", 38f,70f),
 new StandardEyePiece("Omegon", "UWA", 6f,66f),
 new StandardEyePiece("Omegon", "UWA", 9f,66f),
 new StandardEyePiece("Omegon", "UWA", 15f,66f),
 new StandardEyePiece("Omegon", "UWA", 20f,66f),

 new StandardEyePiece("OPT (aka TPO)", "Plossl", 4f,52f),
 new StandardEyePiece("OPT (aka TPO)", "Plossl", 6f,52f),
 new StandardEyePiece("OPT (aka TPO)", "Plossl", 9f,52f),
 new StandardEyePiece("OPT (aka TPO)", "Plossl", 12f,52f),
 new StandardEyePiece("OPT (aka TPO)", "Plossl", 15f,52f),
 new StandardEyePiece("OPT (aka TPO)", "Plossl", 20f,52f),
 new StandardEyePiece("OPT (aka TPO)", "Plossl", 32f,50f),
 new StandardEyePiece("OPT (aka TPO)", "Plossl", 40f,40f),
 new StandardEyePiece("OPT (aka TPO)", "SuperView", 15f,68f),
 new StandardEyePiece("OPT (aka TPO)", "SuperView", 20f,68f),
 new StandardEyePiece("OPT (aka TPO)", "SuperView (Erfle)", 30f,68f),
 new StandardEyePiece("OPT (aka TPO)", "SuperView (Erfle)", 42f,68f),
 new StandardEyePiece("OPT (aka TPO)", "SuperView (Erfle)", 50f,48f),
 //new StandardEyePiece("OpticStar(Ascension Brand)", "Private label various Chinese clones", f,f),
 //new StandardEyePiece("OpticStar (Opticstar Brand)", "Private label various Chinese clones",  f, f),
 //new StandardEyePiece("Orbinar (from Seben),EU/UK, eBay/Amazon seller", "Private label various Chinese clones",  f, f),
 new StandardEyePiece("Orion", "DeepView", 28f,56f),
 new StandardEyePiece("Orion", "DeepView", 35f,56f),
 new StandardEyePiece("Orion", "DeepView", 42f,52f),
 new StandardEyePiece("Orion", "Edge-On Planetary", 3f,55f),
 new StandardEyePiece("Orion", "Edge-On Planetary", 5f,55f),
 new StandardEyePiece("Orion", "Edge-On Planetary", 6f,55f),
 new StandardEyePiece("Orion", "Edge-On Planetary", 9f,55f),
 new StandardEyePiece("Orion", "Edge-On Planetary", 12.5f,55f),
 new StandardEyePiece("Orion", "Edge-On Planetary", 14.5f,55f),
 new StandardEyePiece("Orion", "E-Series", 3.6f,40f),
 new StandardEyePiece("Orion", "E-Series", 6.3f,46f),
 new StandardEyePiece("Orion", "Expanse", 6f,66f),
 new StandardEyePiece("Orion", "Expanse", 9f,66f),
 new StandardEyePiece("Orion", "Expanse", 15f,66f),
 new StandardEyePiece("Orion", "Expanse", 20f,66f),
 new StandardEyePiece("Orion", "LHD", 4f,80f),
 new StandardEyePiece("Orion", "LHD", 6f,80f),
 new StandardEyePiece("Orion", "LHD", 9f,80f),
 new StandardEyePiece("Orion", "LHD", 14f,80f),
 new StandardEyePiece("Orion", "LHD", 20f,80f),
 new StandardEyePiece("Orion", "Q70", 26f,70f),
 new StandardEyePiece("Orion", "Q70", 32f,70f),
 new StandardEyePiece("Orion", "Q70", 38f,70f),
 new StandardEyePiece("Orion", "Sirius", 6.3f,52f),
 new StandardEyePiece("Orion", "Sirius", 7.5f,52f),
 new StandardEyePiece("Orion", "Sirius", 10f,52f),
 new StandardEyePiece("Orion", "Sirius", 12.5f,52f),
 new StandardEyePiece("Orion", "Sirius", 17f,52f),
 new StandardEyePiece("Orion", "Sirius", 20f,52f),
 new StandardEyePiece("Orion", "Sirius", 25f,52f),
 new StandardEyePiece("Orion", "Sirius", 32f,50f),
 new StandardEyePiece("Orion", "Sirius", 40f,40f),
 new StandardEyePiece("Orion", "Stratus", 3.5f,68f),
 new StandardEyePiece("Orion", "Stratus", 5f,68f),
 new StandardEyePiece("Orion", "Stratus", 8f,68f),
 new StandardEyePiece("Orion", "Stratus", 13f,68f),
 new StandardEyePiece("Orion", "Stratus", 17f,68f),

 //new StandardEyePiece("Ostara UK--eBay/Amazon seller", "Private label various Chinese clones",  f, f),
 new StandardEyePiece("Pentax", "SMC-XW", 3.5f,70f),
 new StandardEyePiece("Pentax", "SMC-XW", 5f,70f),
 new StandardEyePiece("Pentax", "SMC-XW", 7f,70f),
 new StandardEyePiece("Pentax", "SMC-XW", 10f,70f),
 new StandardEyePiece("Pentax", "SMC-XW", 14f,70f),
 new StandardEyePiece("Pentax", "SMC-XW", 20f,70f),
 new StandardEyePiece("Pentax", "XF ED", 8.5f,60f),
 new StandardEyePiece("Pentax", "XF ED", 12f,60f),


 new StandardEyePiece("Russell Optics", "Plossl", 50f,30f),
 new StandardEyePiece("Russell Optics", "Research Grade Konig", 7f,60f),
 new StandardEyePiece("Russell Optics", "Research Grade Konig", 10f,65f),
 new StandardEyePiece("Russell Optics", "Research Grade Konig", 12f,70f),
 new StandardEyePiece("Russell Optics", "Research Grade Konig", 18f,67f),
 new StandardEyePiece("Russell Optics", "Research Grade Konig", 18f,70f),
 new StandardEyePiece("Russell Optics", "RKE", 52f,51f),
 new StandardEyePiece("Russell Optics", "RKE", 60f,45f),
 new StandardEyePiece("Russell Optics", "Super plossl", 50f,50f),
 new StandardEyePiece("Russell Optics", "Super plossl", 56f,45f),
 new StandardEyePiece("Russell Optics", "Super plossl", 65f,40f),
 new StandardEyePiece("Russell Optics", "Super plossl", 72f,37f),
 new StandardEyePiece("Russell Optics", "Super plossl", 85f,31f),
 new StandardEyePiece("Russell Optics", "Super Wide Konig", 6.7f,70f),
 new StandardEyePiece("Russell Optics", "Super Wide Konig", 10.5f,65f),
 new StandardEyePiece("Russell Optics", "Super Wide Konig", 13f,70f),
 new StandardEyePiece("Russell Optics", "Super Wide Konig", 19f,70f),
 new StandardEyePiece("Russell Optics", "Super Wide Konig", 19f,70f),

 //new StandardEyePiece("Saxon UK-eBay/Amazon seller", "Private label various Chinese clones", f,f),
 //new StandardEyePiece("Seben (see Orbinar) the seller of Orbinar", "Private label various Chinese clones", f,f),
 //new StandardEyePiece("Sky's the Limit, UK  an eBay merchant", "Private label various Chinese clones",  f, f),
 //new StandardEyePiece("Skywatcher", "Aero ED", 30f,68f),
 new StandardEyePiece("Skywatcher", "Aero ED", 35f,68f),
 new StandardEyePiece("Skywatcher", "Aero ED", 40f,68f),
 new StandardEyePiece("Skywatcher", "ExtraFlat Wide Angle", 16f,60f),
 new StandardEyePiece("Skywatcher", "ExtraFlat Wide Angle", 19f,65f),
 new StandardEyePiece("Skywatcher", "ExtraFlat Wide Angle", 27f,53f),


 new StandardEyePiece("Skywatcher", "Kellner", 25f,50f),
 new StandardEyePiece("Skywatcher", "Kellner", 28f,56f),
 new StandardEyePiece("Skywatcher", "Kellner", 42f,52f),
 new StandardEyePiece("Skywatcher", "LE ", 2f,45f),
 new StandardEyePiece("Skywatcher", "LE ", 9f,50f),
 new StandardEyePiece("Skywatcher", "LE ", 20f,50f),
 new StandardEyePiece("Skywatcher", "LE ", 25f,50f),
 new StandardEyePiece("Skywatcher", "LET", 28f,56f),
 new StandardEyePiece("Skywatcher", "LET", 35f,56f),
 new StandardEyePiece("Skywatcher", "LET", 42f,52f),
 new StandardEyePiece("Skywatcher", "Myriad", 3.5f,110f),
 new StandardEyePiece("Skywatcher", "Myriad", 5f,110f),
 new StandardEyePiece("Skywatcher", "Myriad", 9f,101f),
 new StandardEyePiece("Skywatcher", "Myriad", 20f,100f),
 new StandardEyePiece("Skywatcher", "Nirvana 82", 4f,82f),
 new StandardEyePiece("Skywatcher", "Nirvana 82", 7f,82f),
 new StandardEyePiece("Skywatcher", "Nirvana 82", 16f,82f),
 new StandardEyePiece("Skywatcher", "Nirvana 82", 28f,82f),
 new StandardEyePiece("Skywatcher", "PanaView", 26f,70f),
 new StandardEyePiece("Skywatcher", "PanaView", 32f,70f),
 new StandardEyePiece("Skywatcher", "PanaView", 38f,70f),
 new StandardEyePiece("Skywatcher", "Planetary", 2.5f,58f),
 new StandardEyePiece("Skywatcher", "Planetary", 4f,58f),
 new StandardEyePiece("Skywatcher", "Planetary", 5f,58f),
 new StandardEyePiece("Skywatcher", "Planetary", 6f,58f),
 new StandardEyePiece("Skywatcher", "Planetary", 7f,58f),
 new StandardEyePiece("Skywatcher", "Planetary", 9f,58f),
 new StandardEyePiece("Skywatcher", "Sky Panorama", 7f,82f),
 new StandardEyePiece("Skywatcher", "Sky Panorama", 15f,82f),
 new StandardEyePiece("Skywatcher", "Sky Panorama", 23f,82f),
 new StandardEyePiece("Skywatcher", "Super Lens", 3.6f,40f),
 new StandardEyePiece("Skywatcher", "Super Lens", 10f,52f),
 new StandardEyePiece("Skywatcher", "Super Lens", 20f,52f),
 new StandardEyePiece("Skywatcher", "Super Lens", 25f,50f),
 new StandardEyePiece("Skywatcher", "Super Plossl", 6.3f,52f),
 new StandardEyePiece("Skywatcher", "Super Plossl", 7.5f,52f),
 new StandardEyePiece("Skywatcher", "Super Plossl", 10f,52f),
 new StandardEyePiece("Skywatcher", "Super Plossl", 12.5f,52f),
 new StandardEyePiece("Skywatcher", "Super Plossl", 17f,52f),
 new StandardEyePiece("Skywatcher", "Super Plossl", 20f,52f),
 new StandardEyePiece("Skywatcher", "Super Plossl", 25f,52f),
 new StandardEyePiece("Skywatcher", "Super Plossl", 32f,50f),
 new StandardEyePiece("Skywatcher", "Super Plossl", 40f,40f),
 new StandardEyePiece("Skywatcher", "SWA", 3.5f,70f),
 new StandardEyePiece("Skywatcher", "SWA", 5f,70f),
 new StandardEyePiece("Skywatcher", "SWA", 8f,70f),
 new StandardEyePiece("Skywatcher", "SWA", 13f,70f),
 new StandardEyePiece("Skywatcher", "SWA", 17f,70f),
 new StandardEyePiece("Skywatcher", "SWA", 22f,70f),
 new StandardEyePiece("Skywatcher", "SWA", 32f,70f),
 new StandardEyePiece("Skywatcher", "Wide Angle(also called Ultrawide Angle)", 6f,66f),
 new StandardEyePiece("Skywatcher", "Wide Angle(also called Ultrawide Angle)", 9f,66f),
 new StandardEyePiece("Skywatcher", "Wide Angle(also called Ultrawide Angle)", 15f,66f),
 new StandardEyePiece("Skywatcher", "Wide Angle(also called Ultrawide Angle)", 20f,66f),


 new StandardEyePiece("Stellarvue", "Optimus", 3.6f,110f),
 new StandardEyePiece("Stellarvue", "Optimus", 4.7f,110f),
 new StandardEyePiece("Stellarvue", "Optimus", 9f,100f),
 new StandardEyePiece("Stellarvue", "Optimus", 20f,100f),
 new StandardEyePiece("Stellarvue", "Planetary ", 4.9f,53f),
 new StandardEyePiece("Stellarvue", "Planetary ", 6.1f,53f),
 new StandardEyePiece("Stellarvue", "Plossl", 25f,50f),
 new StandardEyePiece("Stellarvue", "UWA", 4f,82f),
 new StandardEyePiece("Stellarvue", "UWA", 8f,82f),
 new StandardEyePiece("Stellarvue", "UWA", 15f,82f),
 new StandardEyePiece("Stellarvue", "Wide Angle  ", 30f,68f),
 new StandardEyePiece("Sterling (Smart Astronomy)", "Plossl", 4f,55f),
 new StandardEyePiece("Sterling (Smart Astronomy)", "Plossl", 6f,55f),
 new StandardEyePiece("Sterling (Smart Astronomy)", "Plossl", 12.5f,55f),
 new StandardEyePiece("Sterling (Smart Astronomy)", "Plossl", 17f,55f),
 new StandardEyePiece("Sterling (Smart Astronomy)", "Plossl", 20f,55f),
 new StandardEyePiece("Sterling (Smart Astronomy)", "Plossl", 25f,55f),
 new StandardEyePiece("Sterling (Smart Astronomy)", "Plossl", 30f,55f),
 new StandardEyePiece("Sterling (Smart Astronomy)", "Plossl", 40f,55f),
 //new StandardEyePiece("Surplus Shed Miscellaneous eyepieces see site", "Huygens/Kellner/Plossl/Erfle/etc.", 4 to 80mmf,variesf),
 new StandardEyePiece("Takahashi", "Abbe Orthoscopic", 4.00f,44f),
 new StandardEyePiece("Takahashi", "Abbe Orthoscopic", 6f,44f),
 new StandardEyePiece("Takahashi", "Abbe Orthoscopic", 9f,44f),
 new StandardEyePiece("Takahashi", "Abbe Orthoscopic", 12.5f,44f),
 new StandardEyePiece("Takahashi", "Abbe Orthoscopic", 18f,44f),
 new StandardEyePiece("Takahashi", "Abbe Orthoscopic", 25f,44f),
 new StandardEyePiece("Takahashi", "Abbe Orthoscopic", 32f,44f),
 new StandardEyePiece("Takahashi", "Hi-LE", 2.8f,42f),
 new StandardEyePiece("Takahashi", "Hi-LE", 3.6f,40f),
 new StandardEyePiece("Takahashi", "LE", 5f,52f),
 new StandardEyePiece("Takahashi", "LE", 7.5f,52f),
 new StandardEyePiece("Takahashi", "LE", 10f,52f),
 new StandardEyePiece("Takahashi", "LE", 12.5f,52f),
 new StandardEyePiece("Takahashi", "LE", 18f,52f),
 new StandardEyePiece("Takahashi", "LE", 24f,52f),
 new StandardEyePiece("Takahashi", "LE", 30f,52f),
 new StandardEyePiece("Takahashi", "LE", 40f,50f),
 new StandardEyePiece("Takahashi", "LE", 50f,50f),
 new StandardEyePiece("Takahashi", "Ultra Wide/Flat Field", 3.3f,90f),
 new StandardEyePiece("Takahashi", "Ultra Wide/Flat Field", 5.7f,90f),
 new StandardEyePiece("Takahashi", "Ultra Wide/Flat Field", 7f,90f),
 new StandardEyePiece("Takahashi", "Ultra Wide/Flat Field", 10f,90f),
 new StandardEyePiece("TAL", "SuperPlossl", 6.3f,45f),
 new StandardEyePiece("TAL", "SuperPlossl", 7.5f,45f),
 new StandardEyePiece("TAL", "SuperPlossl", 10f,45f),
 new StandardEyePiece("TAL", "SuperPlossl", 12.5f,45f),
 new StandardEyePiece("TAL", "SuperPlossl", 17f,45f),
 new StandardEyePiece("TAL", "SuperPlossl", 20f,45f),
 new StandardEyePiece("TAL", "SuperPlossl", 25f,45f),
 new StandardEyePiece("TAL", "SuperPlossl", 32f,45f),
 new StandardEyePiece("TAL", "SuperPlossl", 40f,38f),
 new StandardEyePiece("TAL", "SuperWideAngle", 10f,65f),
 new StandardEyePiece("TAL", "SuperWideAngle", 15f,65f),
 new StandardEyePiece("TAL", "SuperWideAngle", 20f,65f),
 new StandardEyePiece("TAL", "UltraWideAngle", 15f,82f),
 new StandardEyePiece("TAL", "UltraWideAngle", 20f,82f),
 new StandardEyePiece("TAL", "UltraWideAngle", 24f,82f),
 new StandardEyePiece("TAL", "UltraWideAngle", 25f,82f),
 new StandardEyePiece("Telescope Service", "ED  ", 3.2f,60f),
 new StandardEyePiece("Telescope Service", "ED  ", 5f,60f),
 new StandardEyePiece("Telescope Service", "ED  ", 8f,60f),
 new StandardEyePiece("Telescope Service", "ED  ", 12f,60f),
 new StandardEyePiece("Telescope Service", "ED  ", 15f,60f),
 new StandardEyePiece("Telescope Service", "ED  ", 18f,60f),
 new StandardEyePiece("Telescope Service", "ED  ", 25f,60f),
 new StandardEyePiece("Telescope Service", "Edge-On Flat Field", 8f,60f),
 new StandardEyePiece("Telescope Service", "Edge-On Flat Field", 12f,60f),
 new StandardEyePiece("Telescope Service", "Edge-On Flat Field", 16f,60f),
 new StandardEyePiece("Telescope Service", "Edge-On Flat Field", 19f,65f),
 new StandardEyePiece("Telescope Service", "Edge-On Flat Field", 27f,53f),
 new StandardEyePiece("Telescope Service", "Erfle", 50f,52f),
 new StandardEyePiece("Telescope Service", "Expanse ED", 3.5f,70f),
 new StandardEyePiece("Telescope Service", "Expanse ED", 5f,70f),
 new StandardEyePiece("Telescope Service", "Expanse ED", 8f,70f),
 new StandardEyePiece("Telescope Service", "Expanse ED", 13f,70f),
 new StandardEyePiece("Telescope Service", "Expanse ED", 17f,70f),
 new StandardEyePiece("Telescope Service", "Expanse ED", 22f,70f),
 new StandardEyePiece("Telescope Service", "Paragon ED", 18f,50f),
 new StandardEyePiece("Telescope Service", "Paragon ED", 30f,69f),
 new StandardEyePiece("Telescope Service", "Paragon ED", 35f,69f),
 new StandardEyePiece("Telescope Service", "Paragon ED", 40f,69f),
 new StandardEyePiece("Telescope Service", "Planetary HR", 2.5f,60f),
 new StandardEyePiece("Telescope Service", "Planetary HR", 3.2f,60f),
 new StandardEyePiece("Telescope Service", "Planetary HR", 4f,60f),
 new StandardEyePiece("Telescope Service", "Planetary HR", 5f,60f),
 new StandardEyePiece("Telescope Service", "Planetary HR", 6f,60f),
 new StandardEyePiece("Telescope Service", "Planetary HR", 7f,60f),
 new StandardEyePiece("Telescope Service", "Planetary HR", 8f,60f),
 new StandardEyePiece("Telescope Service", "Planetary HR", 9f,60f),
 new StandardEyePiece("Telescope Service", "Planetary HR", 15f,60f),
 new StandardEyePiece("Telescope Service", "Planetary HR", 20f,60f),
 new StandardEyePiece("Telescope Service", "Planetary HR", 25f,60f),

 new StandardEyePiece("Telescope Service", "Standard Plossl", 4f,50f),
 new StandardEyePiece("Telescope Service", "Standard Plossl", 6.3f,50f),
 new StandardEyePiece("Telescope Service", "Standard Plossl", 10f,50f),
 new StandardEyePiece("Telescope Service", "Standard Plossl", 12.5f,50f),
 new StandardEyePiece("Telescope Service", "Standard Plossl", 15f,50f),
 new StandardEyePiece("Telescope Service", "Standard Plossl", 17f,50f),
 new StandardEyePiece("Telescope Service", "Standard Plossl", 20f,50f),
 new StandardEyePiece("Telescope Service", "Standard Plossl", 25f,50f),
 new StandardEyePiece("Telescope Service", "Standard Plossl", 32f,50f),
 new StandardEyePiece("Telescope Service", "Standard Plossl", 40f,40f),
 new StandardEyePiece("Telescope Service", "Super Plossl", 4f,52f),
 new StandardEyePiece("Telescope Service", "Super Plossl", 6f,52f),
 new StandardEyePiece("Telescope Service", "Super Plossl", 9f,52f),
 new StandardEyePiece("Telescope Service", "Super Plossl", 12f,52f),
 new StandardEyePiece("Telescope Service", "Super Plossl", 15f,52f),
 new StandardEyePiece("Telescope Service", "Super Plossl", 20f,52f),
 new StandardEyePiece("Telescope Service", "Super Plossl", 25f,52f),
 new StandardEyePiece("Telescope Service", "Super Plossl", 32f,50f),
 new StandardEyePiece("Telescope Service", "Super Plossl", 40f,40f),
 new StandardEyePiece("Telescope Service", "SWA", 5f,100f),
 new StandardEyePiece("Telescope Service", "SWA", 10f,100f),
 new StandardEyePiece("Telescope Service", "SWA", 15f,100f),
 new StandardEyePiece("Telescope Service", "SWA", 21f,100f),
 new StandardEyePiece("Telescope Service", "UWA", 6f,66f),
 new StandardEyePiece("Telescope Service", "UWA", 9f,66f),
 new StandardEyePiece("Telescope Service", "UWA", 15f,66f),
 new StandardEyePiece("Telescope Service", "UWA", 20f,66f),
 new StandardEyePiece("Telescope Service", "UWA 82", 4f,82f),
 new StandardEyePiece("Telescope Service", "UWA 82", 7f,82f),
 new StandardEyePiece("Telescope Service", "UWA 82", 16f,82f),
 new StandardEyePiece("Telescope Service", "UWA 82", 28f,82f),
 new StandardEyePiece("Telescope Service", "Wide Angle", 8f,70f),
 new StandardEyePiece("Telescope Service", "Wide Angle", 12f,70f),
 new StandardEyePiece("Telescope Service", "Wide Angle", 17f,70f),
 new StandardEyePiece("Telescope Service", "Wide Angle", 20f,70f),
 new StandardEyePiece("Telescope Service", "Wide Angle", 26f,70f),
 new StandardEyePiece("Telescope Service", "Wide Angle", 32f,70f),
 new StandardEyePiece("Telescope Service", "Wide Angle", 38f,70f),
 new StandardEyePiece("Telescope Service", "XWA", 3.5f,110f),
 new StandardEyePiece("Telescope Service", "XWA", 5f,110f),
 new StandardEyePiece("Telescope Service", "XWA", 9f,100f),
 new StandardEyePiece("Telescope Service", "XWA", 20f,100f),

 new StandardEyePiece("TeleVue", "DeLite", 3f,62f),
 new StandardEyePiece("TeleVue", "DeLite", 4f,62f),
 new StandardEyePiece("TeleVue", "DeLite", 5f,62f),
 new StandardEyePiece("TeleVue", "DeLite", 7f,62f),
 new StandardEyePiece("TeleVue", "DeLite", 9f,62f),
 new StandardEyePiece("TeleVue", "DeLite", 11f,62f),
 new StandardEyePiece("TeleVue", "DeLite", 13f,62f),
 new StandardEyePiece("TeleVue", "DeLite", 15f,62f),
 new StandardEyePiece("TeleVue", "DeLite", 18.2f,62f),
 new StandardEyePiece("TeleVue", "Delos", 3.5f,72f),
 new StandardEyePiece("TeleVue", "Delos", 4.5f,72f),
 new StandardEyePiece("TeleVue", "Delos", 6f,72f),
 new StandardEyePiece("TeleVue", "Delos", 8f,72f),
 new StandardEyePiece("TeleVue", "Delos", 10f,72f),
 new StandardEyePiece("TeleVue", "Delos", 12f,72f),
 new StandardEyePiece("TeleVue", "Delos", 14f,72f),
 new StandardEyePiece("TeleVue", "Delos", 17.3f,72f),
 new StandardEyePiece("TeleVue", "Ethos", 6f,100f),
 new StandardEyePiece("TeleVue", "Ethos", 8f,100f),
 new StandardEyePiece("TeleVue", "Ethos", 10f,100f),
 new StandardEyePiece("TeleVue", "Ethos", 13f,100f),
 new StandardEyePiece("TeleVue", "Ethos", 17f,100f),
 new StandardEyePiece("TeleVue", "Ethos", 21f,100f),
 new StandardEyePiece("TeleVue", "Ethos SX", 3.7f,110f),
 new StandardEyePiece("TeleVue", "Ethos SX", 4.7f,110f),

 new StandardEyePiece("TeleVue", "Nagler4", 12f,82f),
 new StandardEyePiece("TeleVue", "Nagler4", 17f,82f),
 new StandardEyePiece("TeleVue", "Nagler4", 22f,82f),
 new StandardEyePiece("TeleVue", "Nagler5", 16f,82f),
 new StandardEyePiece("TeleVue", "Nagler5", 31f,82f),
 new StandardEyePiece("TeleVue", "Nagler6", 2.5f,82f),
 new StandardEyePiece("TeleVue", "Nagler6", 3.5f,82f),
 new StandardEyePiece("TeleVue", "Nagler6", 5f,82f),
 new StandardEyePiece("TeleVue", "Nagler6", 7f,82f),
 new StandardEyePiece("TeleVue", "Nagler6", 9f,82f),
 new StandardEyePiece("TeleVue", "Nagler6", 11f,82f),
 new StandardEyePiece("TeleVue", "Nagler6", 13f,82f),
 new StandardEyePiece("TeleVue", "Panoptic", 19f,68f),
 new StandardEyePiece("TeleVue", "Panoptic", 24f,68f),
 new StandardEyePiece("TeleVue", "Panoptic", 27f,68f),
 new StandardEyePiece("TeleVue", "Panoptic", 35f,68f),
 new StandardEyePiece("TeleVue", "Panoptic", 41f,68f),
 new StandardEyePiece("TeleVue", "Plossl", 8f,50f),
 new StandardEyePiece("TeleVue", "Plossl", 11f,50f),
 new StandardEyePiece("TeleVue", "Plossl", 15f,50f),
 new StandardEyePiece("TeleVue", "Plossl", 20f,50f),
 new StandardEyePiece("TeleVue", "Plossl", 25f,50f),
 new StandardEyePiece("TeleVue", "Plossl", 32f,50f),
 new StandardEyePiece("TeleVue", "Plossl", 40f,40f),
 new StandardEyePiece("TeleVue", "Plossl", 55f,50f),
 new StandardEyePiece("UniversityOptics", "70 degree", 10f,70f),
 new StandardEyePiece("UniversityOptics", "70 degree", 15f,70f),
 new StandardEyePiece("UniversityOptics", "70 degree", 20f,70f),
 new StandardEyePiece("UniversityOptics", "70 degree", 26f,70f),
 new StandardEyePiece("UniversityOptics", "70 degree", 32f,70f),
 new StandardEyePiece("UniversityOptics", "70 degree", 38f,70f),
 new StandardEyePiece("UniversityOptics", "80 degree", 11f,80f),
 new StandardEyePiece("UniversityOptics", "80 degree", 15f,80f),
 new StandardEyePiece("UniversityOptics", "80 degree", 16f,80f),
 new StandardEyePiece("UniversityOptics", "80 degree", 20f,80f),
 new StandardEyePiece("UniversityOptics", "80 degree", 30f,80f),
 new StandardEyePiece("UniversityOptics", "HD Ortho Phase II(see Fujiyama)", 4f,43.5f),
 new StandardEyePiece("UniversityOptics", "HD Ortho Phase II(see Fujiyama)", 12f,43.5f),
 new StandardEyePiece("UniversityOptics", "HD Ortho Phase II(see Fujiyama)", 25f,43.5f),
 new StandardEyePiece("UniversityOptics", "82 Degree", 7f,82f),
 new StandardEyePiece("UniversityOptics", "82 Degree", 16f,82f),
 //new StandardEyePiece("Vite/Svbony  eBay/Amazon seller of eyepieces", "Private label various Chinese clones",  f, f),
 new StandardEyePiece("Vixen", "HR", 1.6f,42f),
 new StandardEyePiece("Vixen", "HR", 2f,42f),
 new StandardEyePiece("Vixen", "HR", 2.4f,42f),
 new StandardEyePiece("Vixen", "NPL", 4.00f,50f),
 new StandardEyePiece("Vixen", "NPL", 6f,50f),
 new StandardEyePiece("Vixen", "NPL", 8f,50f),
 new StandardEyePiece("Vixen", "NPL", 10f,50f),
 new StandardEyePiece("Vixen", "NPL", 15f,50f),
 new StandardEyePiece("Vixen", "NPL", 20f,50f),
 new StandardEyePiece("Vixen", "NPL", 25f,50f),
 new StandardEyePiece("Vixen", "NPL", 30f,50f),
 new StandardEyePiece("Vixen", "NPL", 40f,40f),
 new StandardEyePiece("Vixen", "SLV", 2.5f,50f),
 new StandardEyePiece("Vixen", "SLV", 4f,50f),
 new StandardEyePiece("Vixen", "SLV", 5f,50f),
 new StandardEyePiece("Vixen", "SLV", 6f,50f),
 new StandardEyePiece("Vixen", "SLV", 9f,50f),
 new StandardEyePiece("Vixen", "SLV", 10f,50f),
 new StandardEyePiece("Vixen", "SLV", 12f,50f),
 new StandardEyePiece("Vixen", "SLV", 15f,50f),
 new StandardEyePiece("Vixen", "SLV", 20f,50f),
 new StandardEyePiece("Vixen", "SLV", 25f,50f),
 new StandardEyePiece("Vixen", "SSW", 3.5f,83f),
 new StandardEyePiece("Vixen", "SSW", 5f,83f),
 new StandardEyePiece("Vixen", "SSW", 7f,83f),
 new StandardEyePiece("Vixen", "SSW", 10f,83f),
 new StandardEyePiece("Vixen", "SSW", 14f,83f),
 new StandardEyePiece("William Optics", "SPL (Super Planetary Long ER)", 3f,55f),
 new StandardEyePiece("William Optics", "SPL (Super Planetary Long ER)", 6f,55f),
 new StandardEyePiece("William Optics", "SPL (Super Planetary Long ER)", 12.5f,55f),
 new StandardEyePiece("William Optics", "Swan", 9f,72f),
 new StandardEyePiece("William Optics", "Swan", 15f,72f),
 new StandardEyePiece("William Optics", "Swan", 20f,72f),
 new StandardEyePiece("William Optics", "Swan", 25f,72f),
 new StandardEyePiece("William Optics", "Swan", 33f,72f),
 new StandardEyePiece("William Optics", "Swan", 40f,70f),
 new StandardEyePiece("William Optics", "Uwan", 4f,82f),
 new StandardEyePiece("William Optics", "Uwan", 7f,82f),
 new StandardEyePiece("William Optics", "Uwan", 16f,82f),
 new StandardEyePiece("William Optics", "XWA", 3.5f,110f),
 new StandardEyePiece("William Optics", "XWA", 5f,110f),
 new StandardEyePiece("William Optics", "XWA", 9f,101f),
 new StandardEyePiece("William Optics", "XWA", 20f,101f),
 //new StandardEyePiece("Wollensak (Surplus Shed)", "Various eyepieces, stock changes)",  f, f),
 new StandardEyePiece("Zhumell", "Z Series Planetary", 3f,55f),
 new StandardEyePiece("Zhumell", "Z Series Planetary", 5f,55f),
 new StandardEyePiece("Zhumell", "Z Series Planetary", 6f,55f),
 new StandardEyePiece("Zhumell", "Z Series Planetary", 9f,55f),
 new StandardEyePiece("Zhumell", "Z Series Planetary", 12.5f,55f),
 new StandardEyePiece("Zhumell", "Z Series Planetary", 14.5f,55f),
 new StandardEyePiece("Zhumell", "Z Series Planetary", 18f,55f),
        };
        #endregion

    }
}

